apiVersion: v1
kind: ConfigMap
metadata:
  name: watch-keeper-config
  namespace: razee
data:
  RAZEEDASH_URL: "{{{RAZEEDASH_URL}}}"
  START_DELAY_MAX: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: watch-keeper-secret
  namespace: razee
data:
  RAZEEDASH_ORG_KEY: "{{{RAZEEDASH_ORG_KEY}}}"
---
{{{WATCH_KEEPER}}}
---
{{{RAZEEDEPLOY}}}
