version: '3.6'
## run docker-compose -f <this-file> up -d
services:
  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    restart: always
    volumes:
    - /tmp/db_data:/var/lib/postgresql/data
