name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_REGISTRY: quay.io/rh-marketplace
  VERSION: 2.0.2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        export BUILD_TIME=`date '+%Y-%m-%d %H:%M:%S'`
        docker build . --file Dockerfile.ubi --build-arg BUILD_TIME="$BUILD_TIME" --build-arg BUILD_ID="${VERSION}-${GITHUB_RUN_NUMBER}" --tag ${IMAGE_REGISTRY}/razeedash-api:${VERSION}-${GITHUB_RUN_NUMBER} 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: quay.io/rh-marketplace
        username: ${{secrets['quayUser']}}
        password: ${{secrets['quayPassword']}}  
    - name: Push Docker Image
      run: docker push ${IMAGE_REGISTRY}/razeedash-api:${VERSION}-${GITHUB_RUN_NUMBER}
